### ISSUE TITLE
Doesn't run without eslint installed

### ISSUE THREAD

**Issue by fcrick** [dependents/node-dependency-tree#101]
I get this after a fresh install:

```
$ dependency-tree
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module 'eslint/lib/util/traverser'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
```

**Comment by pahen** [comment]
I added a fix for that in Madge, but the fix should probably be in `detective-typescript` instead. Eslint must be installed as a peer dependency when `typescript-eslint-parser` is used. Agree @mrjoelkemp ?

**Comment by pahen** [comment]
See https://github.com/pahen/detective-typescript/pull/14

**Comment by pahen** [comment]
I found out that using `typescript-estree` instead of ´typescript-eslint-parser´ actually solves the problem since it's not dependending on eslint.

**Comment by mrjoelkemp** [comment]
Thanks for reporting @fcrick and thanks @pahen for pushing a fix. This landed in precinct, so a fresh install of dependency-tree should fix it. I'll bump the precinct version for dependency-tree and release a patch as well.

**Comment by pahen** [comment]
Sweeet! Works like a charm. Released Madge v3.4.3 with bumped dependency-tree now.
